---
title: "FAQ"
editor: visual
---

## **What is FoolsFest?**

It's a festive co-created campout. Think of it like a DIY festival.  No production company, no vendors, no paid entertainment, just US doin' our thing and making silly foolish magic! 

## **What is provided at FoolsFest?**

A campsite where you can pitch a tent, hang a hammock, or park a vehicle to sleep in under the shade of beautiful California live oak trees! There are potable water spigots throughout Live Oak Campground and plenty of space, so feel free to spread out and build up. We will have "greeters" to help you find a spot and orient you to the campground when you arrive. 

The campground's bathrooms are within a few minutes' walk from your campsite, with running water, flush toilets, sinks, and showers. The showers are communal style, separated by genders - think gym locker room vibes, with many shower heads in one big open room.

An industrial kitchen is on-site, with a walk-in fridge, sinks, stoves, and greywater disposal. The industrial kitchen will primarily be available for those preparing food and beverage-related contributions for FoolsFest (see below), so please plan to store and prepare all personal food at your campsite, using your own cooking gear. There are no fires allowed in the campground, except for in the fire ring by the kitchen; feel free to roast your weenies there.

There are outlets at all the buildings at Live Oak, plus in a few other scattered power boxes. Extension cords are technically not allowed at Live Oak, so portable battery packs would be useful to bring if you have them. 

## **What do I need to provide?**

Whatever you need to meet your own basic needs that isn't provided above! The two big things to bring are your personal meals and your shelter (tents, hammocks, camper vans, etc.). Other helpful items to put on your packing list: a headlamp, a silly hat, a yoga mat, first aid kit, earplugs, sunscreen, shower sandals, a portable chair, warm layers, and your sense of foolish fun!

## **Will there be a central trash/recycling or do we take out waste with us?**

This is a Pack it in / Pack it out event. Our motto is to leave it better than we found it! If you bring garbage or packaging we ask that you plan to pack it out when you leave. Help by bringing reusable eating utensils, plates, cups, and cloth napkins, and by removing products from packaging and cardboard boxes before coming. Water is available on site so no need for single use plastic water bottles -- bring your reusable water bottles!

## **How much do tickets cost?**

We are not selling tickets to FoolsFest, but we are encouraging attendees to make a donation in the range of \$125-225 based on what you're able to contribute. This will help cover the cost of the venue rental, sound system rentals, operations, and other supplies. We are grateful for whatever you can give!

**Please donate via Venmo, cash, or check. To donate via Venmo please send to \@Matthew-Robbins-16 and include FoolsFest2024 and the name of those you are donating on behalf of in the notes.** To donate via cash or check you can either give to us in person or send it to Matthew Robbins, 930 Cieneguitas Road Santa Barbara, CA 93110.

If we end up in the green, any additional funds will be used for FoolsFests to come, such as to secure a venue for next year!

That said, we would really love for you to join us, so if you can't make a donation, don't let that stop you from attending. Your presence is the #1 gift :)

## **When and where should we plan to arrive? And is it possible to come just for the day or do I have to stay overnight?**

We have the entire campground rented out from Thursday, March 28 - Sunday, March 31. All are welcome to come and go whenever they please. Thursday is the setup day and if you'd like to come then to help out, please contact Erin or Mateo! On Sunday we'll do an all-hands-on-deck cleanup.

There's no requirement to stay overnight, though many thrills, skills, and frills will only be revealed after dark ;)

## **How can I contribute to FoolsFest?**

There are many ways to contribute to FoolsFest! As a DIY co-created "festival", this event is like a blank canvas for you to fill in with your preferred color of paint (or painted body part). There are three primary ways to contribute:

**1) *S*hare your passion!** There will be no paid entertainment at FoolsFest - only us fools! If you're someone who has a skill or passion you'd like to share, we'd love to hear about it. You could play music, dance, share a skill, lead a movement class, do some art, give a talk, put on a workshop, prepare food or drink to share, plan a game, and so much more - the sky's the limit! Any and all forms of silliness and creativity are encouraged. 

**2) Volunteer!** Fools Fest is only happening because YOU will help make it happen. We'll be sending out a survey form closer to the event to gather interest in specific volunteering duties, but we're counting on you to pitch in when you see something that needs to be done. Is there trash on the ground? Pick it up. See someone struggling to put up a tent? Pitch in and give them a hand. Someone cooked you dinner? Clean the dishes!

**3) Participate!** Ultimately, this event is about showing up and just being present :) Enjoy and appreciate our time together, and the things other people are bringing! Get to know your fellow fools! Lend a hand! Tell a joke! Accept a gift! Learn a skill! Dance a jig! Explore Live Oak! Wear a costume! Participation can mean so many things, whether quiet or expressive, both behind-the-scenes and out front. We're so excited to get foolish together!

## **I am interested in sharing food or drink at FoolsFest, do I have to prepare enough for all attendees?**

No, you don't have to bring enough for everyone, just aim for an amount that feels doable to you. People and events will be spread out around the campground, so it will be rare that all participants will be doing the same thing at the same time. Everyone should plan to take care of their own needs.

## **Do I have to share my contribution at my campsite?**

You are welcome to share your contribution at your campsite, or in any common spaces! An industrial kitchen will be available for food and beverage-related contributions, a Public House will be available for events, skillshares, workshops, or any other event-like contributions, and stages will be available for dance, performance, or music-related contributions. There is also a TON of open, free space throughout the campground - be creative, and use whatever space you'd like!

Reach out to Mateo or Erin to let us know what type of contribution you'll be providing, and where you'd ideally like to set it up.  Spur-of-the-moment contributions are also welcomed and there will be a central message board where you can post last minute additions to FoolsFest.

## **Is there a dress code?**

Dress to express! Consider bringing fun, funny, unique costume pieces that make you feel great and may delight your fellow fools. We celebrate bodies of all forms, sizes, shapes, and functions. Nudity and Never-Nudes are welcomed alike! Finally, bring whatever you'll need to stay comfortable in the Great Outdoors - closed-toed shoes and layers aren't a bad idea!

## **How can we help to prevent the spread of illness or COVID-19?**

In any gathering of humans, there is an inherent risk of picking up a nasty bug from someone. If you are sick and worried about getting others sick, you should stay home. We trust you all to take care of yourself and others!

## **Should I be concerned about wildlife at Live Oak Campground?**

*No, though please make sure not to leave any food accessible in your campsite to avoid critters!*

## **Is amplified sound allowed?**

Yes, though please be mindful of your neighbors. Quiet hours begin at 10pm.

## **Are pets allowed?**

There are no pets allowed at FoolsFest.  However, reach out to us if there are special circumstances that make leaving your furry buddy at home a hardship.

## **Are kids allowed?**

Yes! Kids are enthusiastically welcome at FoolsFest. We hope to collectively create kid-friendly spaces ("Kidsville!"), activities, and contributions throughout the weekend. However, just like any trip with kids, FoolsFest with kids may take some extra preparation, planning, and diligence. For instance, there may be suggestive or mature themes present during the festival, depending on the music, events, performances, and other contributions offered. 

## **What's the photo and video policy for FoolsFest?**

To maintain an atmosphere where everyone feels comfortable expressing themselves freely and without worry, you must obtain clear and informed consent from anyone you are photographing before doing so. In addition, you must obtain clear and informed consent from those captured before posting any photos or videos on social media.
