---
title: "Resources"
editor: visual
---

### [**A WC-OBON endorsed molecular methods guide**](https://docs.google.com/spreadsheets/d/1rDubDv8d1tieoLY2NQZedbSR4-8lsIoafH266XKmtTo/edit#gid=1024107459)

*This guide includes information to help decision making for marker gene amplification and sequencing. This includes all protocols from member institutions of WC-OBON.*

### [**rCRUX: A rapid and versatile tool for generating reference libraries in R**](https://urldefense.com/v3/__https://github.com/CalCOFI/rCRUX__;!!Mih3wA!FMJUjlH2h1Yuxw7_q2iqC1r6LOKMjpUuSm6zgU77iYcleNHzvF2OXbB4WjkLC_bb52zwTZNmMEFr1-WE9QNNMj5PTLu-$)

*This tool can generate comprehensive metabarcoding reference libraries for any bespoke locus.*

### [**NOAA 'omics data management guide**](https://github.com/aomlomics/omics-data-management)

*This guide was created to help 'omics users decide which data goes to which repositories (NCEI, NCBI, etc.), and how to deposit their data so that it will be FAIR (findable, accessible, interoperable, and reusable), including following community standards for raw data, processed data, and contextual metadata and environmental data.*

### [**Better Biomolecular Ocean Practices (BeBOP-OBON)**](https://github.com/BeBOP-OBON)

*This resource has repositories that include: Minimum Information about an Omics Protocol (MIOP) specifications, biomolecular protocol templates, protocol examples, and digital assets to connect BeBOP to ODIS & Ocean InfoHub.*
